name: Test App
on: 
  push:
    branches:
      - master
jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.2
      with:
        jestArgs: -ci
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: npm run build
          start: npm start
  