name: Test App
on: 
  push:
    branches:
      - master
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build & Test Application
        uses: actions/setup-node@v3
      - run: yarn install
      - run: yarn run build