name: Test App
on: 
  push:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          install: npm install
          build: npm run build
          start: npm start
  